# Compiler
CC = cc

# Compiler flags
CFLAGS = -Wall -Wextra -Werror

# Source files - either specify all or wildcard *.c
SRCS = ft_isalnum.c ft_isalpha.c ft_isdigit.c \

# Object files
OBJS = $(SRCS:.c=.o)

# Executable name
TARGET = libft.a

RM = rm -rf

all: $(TARGET)

# target depends on objects
$(TARGET):	$(OBJS)
	ar rcs $(TARGET) $(OBJS)

clean:
	$(RM) $(OBJS)

fclean:	clean
	$(RM) $(TARGET)

re:		fclean all

.PHONY: all clean fclean re
